config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'rooms#index'

  resources :rooms, only: %i[index show create] do
    post :join, on: :member
    post :leave, on: :member
  end
  resources :messages, only: [:create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit :append_to_room_chat

  validates :text, presence: true

  private

  def append_to_room_chat
    broadcast_append_to(
      room,
      partial: 'rooms/chat_message',
      locals: { message: self },
      target: :chat
    )
  end
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, uniqueness: { message: 'can join only one room at a time' }
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  has_many :messages, dependent: :restrict_with_exception

  after_create_commit { broadcast_append_to :rooms }
  # after_commit { broadcast_replace_to "room_#{id}" }

  validates :name, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         #  :recoverable,
         :rememberable,
         :validatable

  has_many :participations, dependent: :destroy
  has_many :rooms, through: :participations
  has_many :messages, dependent: :restrict_with_exception
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def create
    message = Message.build(**message_params, user: current_user)
    respond_to do |format|
      if message.save
        format.json { head :no_content }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'chat_form',
            partial: 'rooms/chat_form',
            locals: { room: message.room }
          )
        end
      else
        format.json { render json: message.errors.full_messages, status: :unprocessable_content }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'alerts',
            partial: 'alerts',
            locals: { messages: message.errors.full_messages }
          )
        end
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:room_id, :text)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :find_room, only: %i[show join leave]
  def index
    @rooms = Room.all
  end

  def show; end

  def create
    @room = Room.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room has been successfully created' }
      else
        format.html { redirect_to rooms_path, alert: @room.errors.full_messages }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'alerts',
            partial: 'alerts',
            locals: { messages: @room.errors.full_messages }
          )
        end
      end
    end
  end

  def join
    result = RoomJoiner.call(user: current_user, room: @room)

    if result.success?
      render json: result.data[:room], status: :ok
    else
      render json: { errors: result.errors }, status: :unprocessable_content
    end
  end

  def leave
    result = RoomLeaver.call(user: current_user, room: @room)

    render json: result.data[:room], status: :ok
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def find_room
    # TODO: preload messages and their authors
    @room = Room.preload(:users).find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_alerts.html.erb
<%= turbo_frame_tag :alerts do %>
<ul class="alerts">
    <% Array(messages).each do |message| %>
    <li class="message"><%= message %></li>
    <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShittyDisBack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'alerts', locals: { messages: alert } %>
    <ul class="notices">
      <% Array(notice).each do |message| %>
      <li class="message"><%= message %></li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/rooms/_chat.html.erb
<%= turbo_frame_tag :chat do %>
    <% @room.messages.each do |message| %>
    <%= render partial: 'chat_message', locals: { message: message } %>
    <% end %>
<% end %>
<%= render partial: 'chat_form', locals: { room: @room } %>

app/views/rooms/_chat_form.html.erb
<%= turbo_frame_tag :chat_form do %>
    <%= form_with model: Message do |f| %>
        <%= f.hidden_field :room_id, value: room.id %>
        <%= f.text_field :text %>
        <%= f.submit 'Send' %>
    <% end %>
<% end %>

app/views/rooms/_chat_message.html.erb
<div class="chat-message"><%=message.user.email%>: <%=message.text%></div>

app/views/rooms/_join_leave_button.html.erb
<%= turbo_frame_tag :join_leave_button do %>
    <% if room.users.include?(user) %>
    <%= button_to 'Leave', leave_room_path(room) %>
    <% else %>
    <%= button_to 'Join', join_room_path(room) %>
    <% end %>
<% end %>

app/views/rooms/_room.html.erb
<li><%= link_to room.name, room, data: { turbo_frame: '_top' } %></li>

app/views/rooms/_room_user.html.erb
<%= turbo_frame_tag "room_user_#{user.id}" do %>
<li><%= user.email %></li>
<% end %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<%= turbo_stream_from :rooms %>

<ul>
<%= turbo_frame_tag :rooms do %>
    <% @rooms.each do |room| %>
      <%= render room %>
    <% end %>
<% end %>
</ul>

<%= form_with model: Room do |form| %>
  <%= form.text_field :name %>
  <%= form.submit 'Create' %>
<% end %>

app/views/rooms/show.html.erb
<%= link_to 'Back', rooms_path %>

<%# turbo_stream_from "room_#{@room.id}" %>
<%= turbo_stream_from @room %>
<%= turbo_stream_from [@room, :users] %>
<%= turbo_stream_from [current_user, @room] %>

<%# turbo_frame_tag "room_#{@room.id}" do %>
<%= turbo_frame_tag @room do %>
    <h1><%= @room.name %></h1>

    <ul>
        <%= turbo_frame_tag :room_users do %>
            <% @room.users.each do |user| %>
                <%= render partial: 'room_user', locals: { user: user } %>
            <% end %>
        <% end %>
    </ul>

    <%= render partial: 'join_leave_button', locals: { room: @room, user: current_user } %>
<% end %>

<%= render partial: 'chat' %>